version: "3.3"

services:
  apollo-router:
    build:
      context: ./apollo-router
      dockerfile: Dockerfile
    container_name: mb-apollo-router
    network_mode: host
    ports:
      - 4000:4000
