federation_version: 2

subgraphs:
  book-catalog:
    routing_url: http://localhost:7721/graphql
    schema:
      subgraph_url: http://localhost:7721/graphql
  user:
    routing_url: http://localhost:3001/graphql
    schema:
      subgraph_url: http://localhost:3001/graphql
