version: '3.8'

services:
  user-service:
    container_name: user-service
    restart: always
    healthcheck:
      test: node ./healthcheck.js
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
    ports:
      - ${USER_SERVICE_PORT}:${USER_SERVICE_PORT}
    env_file:
      - ./.env
    environment:
      PORT: ${USER_SERVICE_PORT}
